<a href="https://colab.research.google.com/github/oluwaseuno25/OLUWASEUN_INFO5502_-Summer2022/blob/main/Lab_assignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question1
#####Domain problem 
About the dataset (motivation)
As a movie lover, I am curious about what make  movie to be successful considering the fact that some movies are higly rated while some are not.The following questions come to mind 
The genre of the movie,the ratings/reviews by viewers,budget,and numbers of votes?
**How Data was generated**
The dataset is purely self-contained which was generated by making use of online test dataset generator obtained from (https://wwwonlinedatagenerator.com).
##Step 1
The columns was defined and the field type was auto generated
The first column is movie name under the category of entertainment with movie tile as the format.My dataset is uploaded into github https://raw.githubusercontent.com/oluwaseuno25/Olu-tower/main/Newly%20generated.csv
The second column is movie genre under the category of entertainment with movie genre as the format while the third column is ratings/reviews under the category of numbers with decimal as the format, then range 1-10 was assigned to be auto generated. Next column is director’s name under the category of personal info with field format first name and last name to be auto generated with the ratio of male to female chosen was 9:1. Next column is budget under the category of numbers with field format as integers within the range of 0-250000000. Next column is year under the category of date and time with field format as date (mmm,yyyy) which is from 2000-2022. The next column has vote under the category of numbers with field format as integers within the range of 20000-2000000. The last column is language under the category of location with movie tile as language.
###Step 2 
1000 rows was chosen to be generated
###Step 3
The CSV file saved to desktop and github accordingly.
 
Challenges/Restrictions encountered
-The language cannot be streamlined to the major language used during film production  
-To also reduce the stress the money used in the generator can’t be used due to varying in the preinstalled currency used.
 -The dataset can only be used for this purpose alone (i.e assignment) not for research work because it was generated randomly not complied in reality

In [ ]:
#Question 2
# Data collected to answer the research problem:python code to collect 1000 data samples you discussed above
import pandas as pd
newdata =pd.read_csv("https://raw.githubusercontent.com/oluwaseuno25/Olu-tower/main/Newly%20generated.csv")
newdata.head()
print(newdata)
newdata.drop(newdata.index[1000:1300],0,inplace=True)
newdata

                                   Movie name    year  ratings movie genre  \
0                                  Inside Out   5-Aug     2.42       Drama
1                                    Chocolat   6-Aug     3.47      Sci-Fi
2                        Chronicles of Narnia  10-Jul     1.40    Thriller
3     Fantastic Beasts and Where To Find Them  11-Apr     7.68      Horror
4                               Black Panther  13-Jun     5.66    Thriller
...                                       ...     ...      ...         ...
1295                             Transformers   9-Oct     8.61     Fantasy
1296                         Romeo and Juliet  15-Jun     7.77     Musical
1297                            Blood Diamond  19-May     6.22      Horror
1298                                 Rambo II   8-Dec     5.05   Animation
1299                                Star Wars  15-Aug     6.19      Comedy

         vote    directors name    language
0      409819       Tom Everett      Arabic
1      119754        Harry West   Ukrainian
2     1420862     Kurt Morrison       Hindi
3     1142792      Christy Cork  Vietnamese
4      763692   Anthony Nielson   Hungarian
...       ...               ...         ...
1295  1222472    Marvin Rodgers     English
1296   930664      Boris Harris       Uzbek
1297   828018       Bryon Avery     English
1298  1105567     Anthony Kirby     Russian
1299   388216  Joseph Alldridge         Yue

[1300 rows x 7 columns]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

,Movie name,year,ratings,movie genre,vote,directors name,language
0,Inside Out,5-Aug,2.42,Drama,409819,Tom Everett,Arabic
1,Chocolat,6-Aug,3.47,Sci-Fi,119754,Harry West,Ukrainian
2,Chronicles of Narnia,10-Jul,1.40,Thriller,1420862,Kurt Morrison,Hindi
3,Fantastic Beasts and Where To Find Them,11-Apr,7.68,Horror,1142792,Christy Cork,Vietnamese
4,Black Panther,13-Jun,5.66,Thriller,763692,Anthony Nielson,Hungarian
...,...,...,...,...,...,...,...
995,Rambo II,21-Apr,6.89,Fantasy,729708,Carissa Bailey,Korean
996,Harry Potter and The Chamber Of Secrets,16-Sep,4.28,Fantasy,333267,Benny Whitehouse,Mandarin
997,Pretty Woman,19-Jul,7.97,Action,433683,Joseph Swift,Gan Chinese
998,Ice Age 1,10-Dec,9.76,Drama,1034627,Meredith Cadman,Malaysian
999,Alien,7-Apr,7.05,History,1134151,Ember Ventura,Hungarian

In [2]:
!pip install Faker
from faker import Faker
!pip install namegenerator

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Faker
  Downloading Faker-13.15.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 4.8 MB/s
Requirement already satisfied: typing-extensions>=3.10.0.2 in /usr/local/lib/python3.7/dist-packages (from Faker) (4.1.1)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.7/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.4->Faker) (1.15.0)
Installing collected packages: Faker
Successfully installed Faker-13.15.1
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting namegenerator
  Downloading namegenerator-1.0.6.tar.gz (4.4 kB)
Building wheels for collected packages: namegenerator
  Building wheel for namegenerator (setup.py) ... done
  Created wheel for namegenerator: filename=namegenerator-1.0.6-py3-none-any.whl size=4455 sha256=43f07bfa1f39b1051b6d53028cfae6fe2576b2422aae30edbb4312643151e716
  Stored in directory: /root/.cache/pip/wheels/01/e3/1e/8ae42abacf1026de36d9dd016ffa99c85dbee82737bd388012
Successfully built namegenerator
Installing collected packages: namegenerator
Successfully installed namegenerator-1.0.6

In [4]:
import pandas as pd
import random
import namegenerator

from faker import Faker
from random import randrange
from datetime import datetime

no_of_movies = 1000

fake = Faker('de_DE')

movies = []

for movies_id in range(no_of_movies):
    # Create movie name
    title = (namegenerator.gen())

    # Create release date 
    d1 = datetime.strptime(f'1/1/2000', '%m/%d/%Y')
    d2 = datetime.strptime(f'8/7/2022', '%m/%d/%Y')
    release_date = fake.date_between(d1, d2)

    #create director's name
    name = fake.name()

    # Create genre
    genre = random.choice(["Drama", "Fantasy", "Action.", "Comedy","Horror", "Romance", "Thriller.", "Mystery" ])

    # Create movie ratings 
    ratings = fake.pyfloat(right_digits=2, positive=True, min_value=1, max_value=10)

    #Create language
    language = random.choice(["English", "French", "Hindi.", " Japanese","Spanish", "Italian", "Russia", "Mandarin", "German" ])

    #create viewers vote
    vote = fake.ean(length=8)
    
    #create amount spent
    budget = fake.pyfloat(right_digits=00, positive=True, min_value=2000, max_value=250000)

    movies.append([title, release_date, name, genre, ratings, language, vote, budget])

movies_df = pd.DataFrame(movies, columns=['Movie Title','Released_date','Directors Name', 'Genre','Movie ratings', 'Language','Viewers vote', 'Budget ($)']) 
                
pd.pandas.set_option('display.max_columns', None)
print(movies_df)

                  Movie Title Released_date                 Directors Name  \
0         lanky-brown-warthog    2021-10-17                 Joachim Hiller
1    flabby-carmine-chameleon    2020-05-20                Zdravko Kallert
2        craggy-russet-zonkey    2002-07-24             Jutta Hethur B.Sc.
3            cheeky-gold-slug    2012-02-21                   Margot Gunpf
4           breezy-corn-squid    2004-04-21                 Dragan Haering
..                        ...           ...                            ...
995  sleazy-crimson-binturong    2003-04-18  Univ.Prof. Hannchen Gehringer
996   skimpy-cinnabar-caracal    2009-07-22  Dipl.-Ing. Bogdan Putz B.Eng.
997      goopy-beige-barnacle    2021-10-31             Karl-Hans Schomber
998        stuffy-linen-tiger    2009-03-22                   Radmila Henk
999         blurry-tan-walrus    2019-02-21             Gerhard Stahr MBA.

         Genre  Movie ratings   Language Viewers vote  Budget ($)
0    Thriller.           4.67     Hindi.     36221554    237810.0
1      Action.           9.70   Japanese     01793611    189211.0
2      Romance           2.52    Spanish     75352752    190972.0
3       Horror           3.10   Mandarin     28387565    152963.0
4      Action.           4.20    English     52945380     34313.0
..         ...            ...        ...          ...         ...
995    Mystery           3.29    Spanish     94877977    221691.0
996     Horror           9.29    Italian     31056304    218339.0
997  Thriller.           2.14     German     43596973     36355.0
998      Drama           2.12     Russia     19844411     28711.0
999    Romance           8.41     French     90168727    111567.0

[1000 rows x 8 columns]


#Question 3
Data picked: January Flight Delay Prediction 2019 
Source of data: https://www.kaggle.com/divyansh22/flight-delay-prediction
This data is collected from the Bureau of Transportation Statistics, Govt. of the USA.
Reason for the data: It is used to predict the flight delay at the destination airport specifically for the month of January.
The data has the following attributes:

 i. An identification number assigned by US DOT to identify a unique airline (carrier). 

ii. unique Carrier Code. 

iii.  Destination Airport ID to identify a unique airport.

iv. actual Arrival Time (local time: hhmm)

v. arrival delay indicator, 15 minutes or more 

vi cancelled flight Indicator 

vii. diverted flight Indicator 

viii. distance between airports (miles)

ix. dataset containing all the flights in the month of January 2020.

Brief description of the Data Quality

The column of arrival delay indicator, 15 minutes or more has missing values, the arrival time column has missing values, the column of departure delay indicator, 15 minutes or more also contains missing values, the departure time column has missing values, some values are missing in tail numbers column.
Moreso,some of the data attributes are poorly defined. Columns like OP carriers was repeated

**Data cleaning**
All the headings will be shortened using abbreviation.
**Duplicate removed**:Unwanted column like OP unique carriers and two others were deleted due to repetitions.
**Delete all formating** by eliminating all conditions,spell checking to make the data more presentable.Excess spaces and tab spaces in the  worksheet cells to be eliminated .The tail number can be removed because it has no effect on the outcome of the data. All the missing values removed 

Conclusion

After cleaning the data,the data can be used to answer the questions 
below  
(i) Which day of the week has the most and least delayed? 

(ii) How many cancelled flight in the month? 

(iii) How many diverted flights in the month of January?

(iv) Which day of the month has the most and least delayed?

(v) which is the main goals of the dataset?